install : drivers
	cd drivers; make install
CanonDR5020DR5080  Canonimagerunner7105  DRIVER_TEMPLATE  Makefile  RicohMP1350  RicohPRO1357eanonDR5020DR5080  Canonimagerunner7105  DRIVER_TEMPLATE  Makefile  RicohMP1350  RicohPRO1357ex
